server:
  port: 8080
  jwt_secret: "your-secret-key"

database:
  type: "sqlite"  # 可选: sqlite, mysql, postgres
  sqlite:
    file: "fiber-rbac.db"
  mysql:
    host: "localhost"
    port: 3306
    user: "root"
    password: "password"
    dbname: "fiber_rbac"
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "fiber_rbac"
    sslmode: "disable"

# 日志配置
logger:
  level: "info"  # 日志级别: debug, info, warn, error
  file_path: "logs/fiber-rbac.log"  # 日志文件路径，留空则只输出到控制台

# IP限制配置
ip_limit:
  enabled: true
  whitelist_mode: false
  whitelist:
    - "127.0.0.1"
    - "192.168.1.0/24"
  blacklist:
    - "10.0.0.0/8"
  allowed_networks:
    - "192.168.1.0/24" 