server:
  port: 3000
  jwt_secret: "your-secret-key"

database:
  type: "sqlite" # sqlite, mysql, postgres
  sqlite:
    file: "rbac.db"
  mysql:
    host: "localhost"
    port: 3306
    user: "root"
    password: "password"
    dbname: "fiber_rbac"
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    dbname: "fiber_rbac"
    sslmode: "disable"

# IP限制配置
ip_limit:
  enabled: true  # 是否启用IP限制
  whitelist_mode: false  # true: 只允许白名单中的IP访问, false: 阻止黑名单中的IP访问
  
  # IP白名单列表
  whitelist:
    - 127.0.0.1
    - 192.168.1.100
    
  # IP黑名单列表
  blacklist:
    - 10.0.0.5
    - 192.168.1.200
  
  # 允许的IP网段 (CIDR格式)
  allowed_networks:
    - 192.168.0.0/16  # 192.168.0.0 - 192.168.255.255
    - 10.0.0.0/8      # 10.0.0.0 - 10.255.255.255 